version: "3.9"

services:

  # PostgreSQL
  db:
    image: postgres:16-alpine

  # MinIO (store for images)
  minio:
    image: minio/minio:latest

  # Redis (broker)
  redis:
    image: redis:7-alpine

  # Django backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://mdt:mdt_secret@db:5432/mdt
      REDIS_URL: redis://redis:6379/0
      MINIO_ENDPOINT: minio:9000
      ML_SERVICE_URL: http://ml-service:8001
    depends_on:
      db:
      redis:
      minio:
      worker:

  # Celery worker
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery
    environment:
      DATABASE_URL: postgres://mdt:mdt_secret@db:5432/mdt
      REDIS_URL: redis://redis:6379/0
      MINIO_ENDPOINT: minio:9000
      ML_SERVICE_URL: http://ml-service:8001
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  # ML Inference Service
  ml-service:
    build:
      context: ./ml_service
      dockerfile: Dockerfile

  # Nginx (reverse proxy + frontend SPA)
  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    depends_on:
      - backend
      - ml-service
