# Generated by Django 6.0.3 on 2026-03-06 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receiver', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_builtin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_tag', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('staging', 'Staging'), ('active', 'Active'), ('rollback', 'Rollback'), ('archived', 'Archived')], default='staging', max_length=20)),
                ('confidence_threshold', models.FloatField(default=0.5)),
                ('artifact_path', models.CharField(max_length=500)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CameraSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_width', models.PositiveIntegerField(default=1920)),
                ('resolution_height', models.PositiveIntegerField(default=1080)),
                ('capture_interval_seconds', models.FloatField(default=5.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='receiver.camera')),
            ],
        ),
        migrations.CreateModel(
            name='RetrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('dataset_size', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraining_jobs', to='administration.modelversion')),
                ('initiated_by', models.ForeignKey(limit_choices_to={'role': 'administrator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraining_jobs', to=settings.AUTH_USER_MODEL)),
                ('result_model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_by', to='administration.modelversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
