# Generated by Django 6.0.3 on 2026-03-06 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receiver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_model_version', models.CharField(blank=True, max_length=50)),
                ('raw_response', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detection', to='receiver.inspectionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='DetectedDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_type', models.CharField(choices=[('RS', 'Rolled-in Scale (RS)'), ('Pa', 'Patches (Pa)'), ('Cr', 'Crazing (Cr)'), ('PS', 'Pitted Surface (PS)'), ('In', 'Inclusion (In)'), ('Sc', 'Scratches (Sc)'), ('other', 'Other')], max_length=20)),
                ('bbox_x', models.FloatField()),
                ('bbox_y', models.FloatField()),
                ('bbox_w', models.FloatField()),
                ('bbox_h', models.FloatField()),
                ('confidence', models.FloatField(help_text='ML confidence score [0, 1].')),
                ('is_active', models.BooleanField(default=True)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='detection.defectdetection')),
            ],
            options={
                'ordering': ['-confidence'],
            },
        ),
    ]
